src/globals.php
Just a little typo in a doc block!
=> Fix typo in beforeAll() PHPDoc block

.github/workflows/tests.yml
This fixes #36, and gets the test suite running, however there might be an underlying issue with paths in Windows. 🤔
https://github.com/owenvoke/pest/runs/715929243
=> Fix Windows builds running Pest

.github/workflows/formats.yml, .github/workflows/tests.yml, bin/pest, composer.json, src/Factories/TestCaseFactory.php, src/PendingObjects/UsesCall.php, src/Support/Backtrace.php, src/TestSuite.php, tests/.snapshots/success.txt, tests/Fixtures/DirectoryWithTests/ExampleTest.php, tests/Fixtures/ExampleTest.php, tests/Visual/SingleTestOrDirectory.php, tests/Visual/Success.php
Based on https://github.com/pestphp/pest/pull/41 and all tests for `test:unit` pass under Windows and Linux.
It fixes issues, where otherwise some features wouldn't load or work at all under Windows.
=> Fixes autoloading, plugins and tests on Windows

src/Support/Backtrace.php
With this PR, we prevent PHP from populating the backtrace with all the functions/methods arguments.
This PR can have little to BIG effects, depending on when `Backtrace::file()`  and `Backtrace::file()` are called, so chance are that at some point this can save a lot of memory, considering the fact that they are called *really* often, afaik.
I did some benchmarking and it saves between nothing and 6MB (with tests and logic) (using Blackfire). Ofc, it doesn't mean a lot because benchmarking will depends on a bunch of things.
Quoting [php.net](https://www.php.net/manual/en/function.debug-backtrace.php):
> DEBUG_BACKTRACE_IGNORE_ARGS : Whether or not to omit the "args" index, and thus all the function/method arguments, **to save memory**.
=> Optimise debug_backtrace calls

.github/workflows/tests.yml
As per comments in Discord, this adds ["Problem matchers"](https://github.com/actions/toolkit/blob/master/docs/problem-matchers.md#problem-matchers) for PHP and PHPUnit.
As far as I can tell, the PHPUnit matcher should work fine with Pest. But if there are any issues in future, we can always generate our own [matcher config](https://raw.githubusercontent.com/shivammathur/setup-php/master/src/configs/phpunit.json).
See: https://github.com/marketplace/actions/setup-php-action#problem-matchers
=> Add problem matcher output to CI

.gitignore, src/Repositories/TestRepository.php, tests/.snapshots/success.txt, tests/Autoload.php, tests/Plugins/Traits.php
While loading the class or traits & groups for the given path it overrides the previous configuration. The pest plugins where not loading the traits with the Plugin::use() method.
=> Fix in Test Repository use method.

.github/workflows/changelog.yml
See: https://github.com/pestphp/website/pull/66#discussion_r447211656
This makes sure that the "Next section" link is included in the website changelog.
=> Add next section link to the CHANGELOG

composer.json, src/Plugins/Thanks.php, tests/.snapshots/success.txt, tests/Unit/Plugins/Thanks.php
| Fixed tickets | #116
This adds the `--thanks` option as shown below:
---
As the plugin uses `exit(0)`, I wasn't sure how best to write the test for it as it just kills the test-suite.
Closes #116
=> Add --thanks option plugin

.github/workflows/changelog.yml
This updates the changelog action to add an `<hr/>` tag to the end of the changelog so that the "next section" link isn't so close.
**Without `<hr/>` tag**
**With `<hr/>` tag**
=> Add 'hr' tag to separate link

src/Expectation.php
| Fixed tickets | -
- Streamlined comments
- Removed potential confusion between `$value` & `$this->value`: now we use `$expected` & `$this->value`
=> Polishing Expectation API

src/Laravel/Commands/PestInstallCommand.php
This PR makes the `pest:install` command correctly handle the `--no-interaction` flag by avoiding the call of the invokable class `\Pest\Console\Thanks` if said flag is defined. 
For context, I was making a preset, and because of that command, the preset was hanging. 
Note that I decided to completely avoid the `Thanks` process if the `--no-interaction` flag was set because I figured that if it was defined, the user wouldn't read that command's output, but if you want, I can change the code so that `Thanks` runs but doesn't ask the question. 
Additionnal note, the linting fails on my Windows machine because of line endings. Not sure how to fix that (I know it's on my end). Everything else passes, though.
=> Avoid command interactions when the `--no-interaction` flag is given

.github/workflows/static.yml, .github/workflows/tests.yml, composer.json, phpstan.neon, src/Actions/ValidatesConfiguration.php, src/Factories/TestCaseFactory.php, src/PendingObjects/TestCall.php, src/Support/Container.php, src/Support/HigherOrderMessage.php, src/Support/Reflection.php, tests/.snapshots/success.txt
| Fixed tickets | #127
This PR:
* Drops support for PHPUnit less than 9.3
* Adds support for PHP 8.0
Note that PHP 8.0.0-beta1 will be released on [Aug 06 2020](https://wiki.php.net/todo/php80) and PHPUnit 9.3.0 on [Aug 07 2020](https://github.com/sebastianbergmann/phpunit/milestone/38). I think this PR should be released simultaneously with PHPUnit 9.3.
=> feat: adds support to phpunit 9.3 and php 8.0

composer.json
Once we are sure, there will be no more breaking changes to internal classes on 9.3.x, we could relax this version constraint, but for now, we will pin the exact version we want, and upgrade it as needed.
=> Require PHPUnit 9.3.7

src/Expectation.php, tests/.snapshots/success.txt, tests/Expect/toBeFile.php, tests/Expect/toBeReadableDirectory.php, tests/Expect/toBeReadableFile.php, tests/Expect/toBeWritableFile.php
This adds 3 new methods to the assertions API that matches the `toBeDirectory*` methods.
- `toBeFile()`
- `toBeReadableFile()`
- `toBeWritableFile()`
I've also fixed the test case for `toBeReadableDirectory()` as it was running the wrong methods.
https://github.com/pestphp/pest/commit/d5a7becb54df1594381101a41cd6a5d6564727c7
---
For some reason, the snapshot validation isn't working despite me regenerating it. Not really sure how to resolve this...
=> feat(expectations): add file assertions

src/Pest.php, tests/Unit/Plugins/Version.php
I think this makes more sense when using the development (`dev-master`) version of Pest. It seems a bit odd running Pest `^0.3` and seeing `0.2.2` in the output. Especially as this wasn't updated in the [`v0.2` branch](https://github.com/pestphp/pest/blob/v0.2.x/src/Pest.php), so it shows `0.2.2` even when using Pest `0.2.3` or `0.2.4`.
I've also used the `Pest\version()` function in the test which means that the hardcoded string doesn't have to be updated after each release.
=> chore: indicate 0.3 dev in version

bin/pest
This makes sure that the `Output` class in the container is following the provided `--colors` flag.
Currently without this change, using `--colors=never` still uses colours in the output:
With this change, plugins will follow the `--colors=never` configuration:
---
As displayed in the screenshots, this only applies to plugins that are using the container instance. I know there are other references that will not obey this ([in Collision](https://github.com/nunomaduro/collision/blob/424a2ff61dccf0f98fbefaec252d444411b4bf83/src/Adapters/Phpunit/Style.php#L55) as mentioned in https://github.com/pestphp/pest/pull/51), but this should make it better for plugins.
=> fix: don't decorate output if --colors=never is set

tests/.snapshots/success.txt, tests/Visual/Success.php
This updates the snapshot generation for visual tests to remove the time value in the snapshot output as this causes issues when re-generating for anyone doing a PR.
=> fix: update snapshot generation to strip time

src/Support/Reflection.php, tests/.snapshots/success.txt, tests/Autoload.php, tests/Features/Helpers.php
```php
// tests/Helpers.php
function assertSomething() {}
```
```php
// tests/SomeTest.php
it('works')->assertSomething();
```
Right now, any functions can be called like `substr` or `dd`, maybe we want to restrict that behavior to function asserting something. (if there is no new assertions, we still throw a BadMethodCallException) ?
This is still WIP but it works, without breaking any existing test.
=> Forward TestCase bad method calls to global functions

README.md
The badge was pointing at the old test suite name. 👍🏻
=> docs: fix GitHub Actions badge in README

src/Expectation.php, tests/.snapshots/success.txt, tests/Expect/toEndWith.php, tests/Expect/toStartWith.php
=> feat: add 'toStartWith' and 'toEndWith' expectations

src/Expectation.php, tests/.snapshots/success.txt, tests/Expect/toMatchConstraint.php
This allows the use of [Constraint classes](https://github.com/sebastianbergmann/phpunit/tree/master/src/Framework/Constraint) for more complex validation.
```php
// From basic constraints
expect(true)->toMatchConstraint(new IsTrue());
// To more complex constraints
expect(true)->toMatchConstraint(
$this->logicalAnd(
$this->logicalNot(new IsFalse()),
new IsType(IsType::TYPE_BOOL)
)
);
// To custom constraints
expect('https://google.com')->toMatchConstraint(new IsValidUrlConstraint());
class IsValidUrlConstraint extends PHPUnit\Framework\Constraint
{
public function toString()
{
return 'is a valid url';
}
protected function matches($other): bool
{
if (! is_string($other)) {
return …
```
=> feat(expectations): add toMatchConstraint

src/Expectation.php, tests/.snapshots/success.txt, tests/Expect/toMatch.php, tests/Expect/toMatchRegEx.php
I wasn't sure about the naming of this, whether it should be `toMatchRegEx`, `toMatchRegExp`, or `toMatchRegularExpression`. (The `toBe*` prefix doesn't really work with any of them).
=> feat(expectations): add toMatch

src/Support/HigherOrderMessageCollection.php, tests/.snapshots/success.txt, tests/Features/HigherOrderTests.php, tests/Features/Skip.php
| Fixed tickets | #184 
This fixes higher order tests where an assert is followed by any other higher order message. This is due to the fact that the PHPUnit assert methods (located in `vendor/phpunit/phpunit/src/Framework/Assert.php`) return void.
=> Revert to original target if new target is null

src/Datasets.php, tests/.snapshots/success.txt, tests/Features/Datasets.php, tests/Unit/Datasets.php
| Fixed tickets | 
With named datasets, Pest does not currently include the dataset name in test output. This PR inserts the dataset name in the dataset description, so that the output of both the test result and failure messages mimic the PHPUnit format.
For example, given the test:
```
test('same pest style', function ($val) {
$this->assertSame(1, $val);
})->with([
'one' => [1],
'two' => [2],
]);
```
the current output includes:
```
✓ same with (1)
⨯ same with (2)
---
• Tests\Unit\Datasets > same with (2)
```
With this PR, the new output is:
```
✓ same with data set "one" (1)
⨯ same with data set "two" (2)
---
• Tests\Unit\Datasets > same with data set "two" (2)
```
The PHPUnit failure output, for a …
=> Add name to description for named datasets

src/Console/Command.php
This PR adds the pest version when running help.
=> Add Pest version to help command

composer.json
| New feature?  no
| Fixed tickets | #205 
allow all phpunit versions greater or equal to 9.3.7
=> Update phpunit dependency constraint

src/TeamCity.php
Our teamcity printer didn't do the cleanup on the exception which phpunit does, so I added that in.
```php
it("fails", function () {
throw new Exception("fails");
});
```
It still does not use collision, as I cannot figure out how to make that work. However this will at least help a lot of users with debugging their exceptions.
New result:
Old result:
=> Improve exception output in teamcity printer

src/PendingObjects/TestCall.php, tests/.snapshots/success.txt, tests/Features/Depends.php
| Fixed tickets | fixes #213
This resolves #213, although it needs some thorough testing.
The issue is that [`ExecutionOrderDependency::createFromDependsAnnotation()`](https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/ExecutionOrderDependency.php#L46) splits the provided test name by spaces in order to determine the ["clone option"](https://phpunit.readthedocs.io/en/9.3/writing-tests-for-phpunit.html#writing-tests-for-phpunit-test-dependencies). We currently use this in the [`TestCall::depends()`](https://github.com/pestphp/pest/blob/d85432933cfd916f691a564ccd10dab82d008dd6/src/PendingObjects/TestCall.php#L98) method, so when depending on a test with spaces in the name, you need to …
=> fix(depends): resolve issue with dependency names

composer.json, src/Laravel/Commands/PestDuskCommand.php, src/Laravel/PestServiceProvider.php
This new command will replicate Dusk behavior with .env.dusk files
| Fixed tickets | #212
Laravel Dusk has a feature to replace current `.env` file with a specific one depending on your environment, this PR replicate this feature in Pest.
Link to the Dusk feature: https://laravel.com/docs/8.x/dusk#environment-handling
I'm not sure of my implementation as I had to install `laravel/dusk` as a dev dependency, but if I'm not installing it I'm getting error from rector as it doesn't find the class.
Should I disable lint for this file or is there a better way to do it?
=> Add a dusk command for Laravel

src/Concerns/Extendable.php, src/Expectation.php, src/Support/Extendable.php, src/globals.php, tests/.snapshots/success.txt, tests/Expect/extend.php
This pull request proposes yet another alternative to (#186) and (#228) adding the following API for add methods to `expect()`:
```php
expect()->extend('toBeWithinRange', function ($min, $max) {
return $this->toBeGreaterThanOrEqual($min)->toBeLessThanOrEqual($max);
});
test('numeric ranges', function () {
expect(100)->toBeWithinRange(90, 110);
});
```
=> feat: makes expect extendable

src/Datasets.php, src/Factories/TestCaseFactory.php, src/PendingObjects/TestCall.php
When using dataset with string as array key in projects, PHPStan refuses because of:
```
$ vendor/bin/pest
PASS  Tests\Unit\DatasetTest
✓ it tests with string key for dataset with data set "with value `true`" (true)
Tests:  1 passed
Time:   0.04s
$ vendor/bin/phpstan analyze
------ ---------------------------------------------------------------------------------------------------------------------------------------------------------- 
Line   tests/Unit\DatasetTest.php                                                                                                                
------ --------------------------------------------------------------------------------------------------------------------------- …
```
=> fix: authorize string as key for datasets

bin/pest
| Fixed tickets | https://github.com/pestphp/pest-intellij/issues/73
So this is not necessarily something we want to support, so wanna get the rest of your guys feedback on it.
So basically the issue is that @NickSdot has a pretty strange folder structure, where the root of the project is actually not the root of php application.
The phpstorm plugin set's the CWD to be the project root, however Pest expects CWD to be the php application's root. This can prob. be solved in the plugin by changing the CWD to the php application root.
The solution in this pr is created by @NickSdot.
It basically suggests a structure where we guess the php application root from the composer autoloader path instead. This …
=> Get root path based on composer autoloader

src/Concerns/TestCase.php, src/Factories/TestCaseFactory.php, src/PendingObjects/TestCall.php, tests/.snapshots/success.txt, tests/Features/DependsInheritance.php
| Fixed tickets | #230
As requested in #230. This pull request contains a failing test demonstrating that test class inheritance via `uses` does not work when `depends` is called.
I added the tests in a separate file in order not to break the tests in `Depends.php`.
=> Add test for inheritance with depends

src/Laravel/Commands/PestDuskCommand.php
In windows not work
full path is used in [https://github.com/laravel/dusk/blob/7e05b3ca4f17afcba528c4c5a2390a2dd9949b38/src/Console/DuskCommand.php#L91](https://github.com/laravel/dusk/blob/7e05b3ca4f17afcba528c4c5a2390a2dd9949b38/src/Console/DuskCommand.php#L91) and [https://github.com/nunomaduro/collision/blob/163d5c2bd8fe5072b942627980d20831dfd9de78/src/Adapters/Laravel/Commands/TestCommand.php#L108](https://github.com/nunomaduro/collision/blob/163d5c2bd8fe5072b942627980d20831dfd9de78/src/Adapters/Laravel/Commands/TestCommand.php#L108)
=> change binary path pest:dusk

src/PendingObjects/TestCall.php
| Fixed tickets | #250
The current phpDoc refers to a type that doesn't exist, it's a mistake, I fixed it to the correct type.
=> Fix `TestCase@expect` phpDoc

src/Concerns/TestCase.php, src/Console/Command.php, src/PendingObjects/UsesCall.php, src/Repositories/TestRepository.php, src/Support/ChainableClosure.php, tests/.snapshots/success.txt, tests/Hooks/AfterAllTest.php, tests/Hooks/AfterEachTest.php, tests/Hooks/BeforeAllTest.php, tests/Hooks/BeforeEachTest.php, tests/Pest.php
| Bug fix?      | `no`
| New feature?  | `yes`
| Fixed tickets | #255 
- add global/shared hooks that are configurable in `Pest.php` similar to `groups` through the `uses()` function;
- `beforeEach(Closure $hook)`
- `beforeAll(Closure $hook)`
- `afterEach(Closure $hook)`
- `afterAll(Closure $hook)`
- add new helper function to `ChainableClosure` to create static instances;
- `fromStatic(Closure $closure, Closure $next): Closure`
- load test structure in `run` before we calling the parent's `run` method, instead of in `createRunner`
- add tests for each new uses hook;
=> Reusable hooks

bin/pest, src/Actions/LoadStructure.php, src/Laravel/Commands/PestDatasetCommand.php, src/Laravel/Commands/PestInstallCommand.php, src/Laravel/Commands/PestTestCommand.php, src/Pest.php, src/Plugin.php, src/TestSuite.php, tests/Unit/Actions/AddsTests.php, tests/Unit/Support/Container.php, tests/Unit/TestSuite.php
| Fixed tickets | #194
> This is an implementation to make the test directory configurable as requested in https://github.com/pestphp/pest/issues/194.
It does so by introducing a new `--test-directory` argument. If this flag is set you can call `Pest\testDirectory` which will return the path value and optionally concatenate it with a filename. Calling `testDirectory('directory/File.php')` will return `tests/directory/File.php` by default.
```php
// When using an invalid directory
❯ bin/pest --test-directory=blarbs
Pest\Exceptions\InvalidUsesPath
The path `/Users/brian/Work/fork/blarbs` is not valid.
```
=> make test directory configurable

phpstan.neon, src/Actions/AddsDefaults.php, src/Logging/JUnit.php, src/Logging/TeamCity.php
| Bug fix?      | Kinda
| Fixed tickets | #48 
This PR adds support for Junit reporting.
Junit is used by many third party tools to look into the tests.
In this specific instance I want to add Junit so we can have support for infection php as they rely on junit format.
Adding the support for Pest into infection will not be part of pest codebase and this part will @maks-rafalko do for us.
=> Add Junit support

src/Laravel/Commands/PestDatasetCommand.php, src/Laravel/Commands/PestInstallCommand.php, src/Laravel/Commands/PestTestCommand.php
This should resolve the issue with all Pest Laravel commands (except `pest:dusk` as far as I know) failing.
=> fix: resolve test directory before function call

src/Exceptions/MissingDependency.php, src/Functions.php, src/Mock.php, tests/.snapshots/success.txt, tests/Features/Helpers.php, tests/Features/Mocks.php, tests/Helpers.php
**Note: Fell free to ask me if you would like to keep working on this pull request. This is just a POC, that I've done in 10 minutes. I may have no time to work on this in the future.**
This pull request adds a POC about what could eventually be built-in mocks in Pest. At this time, the code doesn't do much. But the goal is to provide the following API:
```php
it('can mock methods', function () {
$mock = mock(Http::class)->expect(
get: 'foo',
);
expect($mock->get())->toBe('foo');
});;
```
Of course, this is multiple questions here: like how to provide and method expectation without return values, how to define the number of times a method expectation should happen, etc.
=> feat: adds built-in mocking

src/Datasets.php, tests/Unit/Datasets.php
| Fixed tickets | #238 
**This PR implements the solution proposed by @Ilyes512, all the credits goes to him**
As described in #238 , for complex datasets, for the sake of readability it should be better to display the dataset name over the actual values, in order to avoid some unreadable log:
The issue was closed even if after a while the solution was accepted as fine by @owenvoke (https://github.com/pestphp/pest/issues/238#issuecomment-750400639) and marked as an enhancement.
I think the closed status could have caused the enhancement to be "forgotten", so I think it could be a nice idea to bring it back up.
@Ilyes512 solution is simple: showing the dataset name if it is present, otherwise showing the …
=> hides dataset values if they have a name

composer.json
This is mainly to lock the Expectations plugin to `^1.3` as anything that uses `^1.0` of Pest, with `--prefer-lowest` and is using the `sequence()` method will fail due to an undefined method.
This makes sure that in the next version of Pest, people wanting to use the `sequence()` expectation can just require Pest `^1.4` or whatever.
The alternative would be for them to require `pestphp/pest-plugin-expectations:^1.3` in their own `composer.json`, but as a 1st-party plugin I thought it would be good to add it here.
=> chore(deps): update minimum plugin versions

src/Datasets.php, src/Factories/TestCaseFactory.php, src/PendingObjects/TestCall.php, tests/.snapshots/success.txt, tests/Features/Datasets.php, tests/Unit/Datasets.php
| Fixed tickets | -
**my aim is to allow a test to be written like this one:**
```php
it('uses a matrix of datasets', function($a, $b){
expect($a * $b)->toBeNumeric();
})->with([1, 2, 3, 4])->with([5, 6, 7, 8]);
it('uses a matrix of datasets with variadic arguments', function($a, $b){
expect($a * $b)->toBeNumeric();
})->with([1, 2, 3, 4], [5, 6, 7, 8]);
```
this will generate a matrix of combination of the two datasets (cartesian product) 
**this feature allows even more than two datasets:**
```php
it('uses 3D matrix of datasets', function($a, $b, $c){
expect($a * $b * $c)->toBeNumeric();
})->with([1, 2, 3, 4])->with([5, 6])->with([7, 8]);
it('uses again a 3D matrix of datasets', function($a, $b, $c){ …
```
=> Matrix datasets

.gitattributes, composer.json, src/Plugins/Init.php, stubs/init/ExampleTest.php, stubs/init/Pest.php, stubs/init/phpunit.xml
This moves the Pest Init plugin into Pest core.
Part of https://github.com/pestphp/pest/issues/316.
=> feat: move init command out of external plugin

composer.json, src/Plugins/Coverage.php, src/Support/Coverage.php, tests/.snapshots/success.txt, tests/Features/Coverage.php
This moves the Pest Coverage plugin into Pest core.
Part of https://github.com/pestphp/pest/issues/316.
=> feat: move Coverage out of external plugin

src/Expectation.php, src/Support/Arr.php, tests/.snapshots/success.txt, tests/Features/Expect/toHaveKey.php, tests/Features/Expect/toHaveKeys.php
This is a copy of https://github.com/pestphp/pest-plugin-expectations/pull/15 after plugins have been moved into Pest core.
One change I made was to relocate the `Arr` class to `Support\Arr` so that it can be used by other Pest features in the future if desired.
=> Reimplements the new `toHaveArray` features.

src/Expectation.php, tests/.snapshots/success.txt, tests/Features/Expect/json.php
Allows to parse a JSON string to array and access it when using Higher Order expectations.
```php
//Propose
expect('{"name":"Nuno"}')->json()->name->toBe('Nuno');
//Instead of 
expect(json_decode('{"name":"Nuno"}'), true)->name->toBe('Nuno');
```
=> Method json() to parse JSON strings

src/Expectation.php, tests/.snapshots/success.txt, tests/Features/Expect/sequence.php
This is a port of https://github.com/pestphp/pest-plugin-expectations/pull/16 after plugins were merged into core.
=> Sequenced expectations can now be passed as non-callable values

composer.json
This will solve the issue
/cc @owenvoke @nunomaduro we need to figure out this whenever `phpunit/phpunit` is upgraded the CI starts failing until pest fix it 🤔
=> Update phpunit/phpunit to 9.5.6

src/HigherOrderExpectation.php, tests/.snapshots/success.txt, tests/Features/Expect/HigherOrder/methodsAndProperties.php
This is kind of a bug fix, but I prefer to think of it as a new feature 😆 
Previously, calling the `and` method in a Higher Order expectation would fail because the original Higher Order expectation was still the target. This PR now allows for the following:
```php
it('can start a new higher order expectation using the and syntax', function () {
expect(new HasMethodsAndProperties())
->toBeInstanceOf(HasMethodsAndProperties::class)
->meta->toBeArray
->and(['foo' => 'bar'])
->toBeArray()
->foo->toEqual('bar');
});
```
=> Allows `and` in Higher Order Expectations.

src/PendingObjects/TestCall.php, src/Plugins/Coverage.php, src/Support/HigherOrderCallables.php, src/Support/HigherOrderMessage.php, src/Support/Reflection.php, tests/.snapshots/success.txt, tests/Features/HigherOrderTests.php
Let's face it, Higher Order tests are the bomb. I love them. But occasionally, I'll need to nip into the test case for something or call a method that can't be called immediately (like the `route` method in Laravel).
This PR adds a new `tap` method, which provides this functionality:
```php
it('can tap into the test')
->expect('foo')->toBeString()->toBe('foo')
->tap(function () { expect($this)->toBeInstanceOf(TestCase::class); })
->and('hello world')->toBeString();
```
If you return from the `tap` method, you can actually springboard off of that for the rest of the higher order test:
```php
it('can return from a tap')
->tap(fn () => expect(route('welcome')))
->toStartWith('https://');
```
Excited to hear …
=> Adds a new `tap` method to Higher Order tests

src/PendingObjects/TestCall.php, src/Plugins/Coverage.php, src/Support/HigherOrderMessage.php, src/Support/HigherOrderMessageCollection.php, tests/Features/Skip.php
Hey y'all,
something that came up in the stream yesterday was this:
```php
public function requiresPostgreSQL(): void
{
if (DB::getDriverName() !== 'pgsql') {
$this->markTestSkipped('This test requires a PostgreSQL database connection');
}
}
```
Obviously, this condition requires the test case setup method to already have been run, so you wouldn't be able to write it in Pest's `skip` method. This PR enables this functionality by moving the conditional logic into the HigherOrderMessage itself, and binding the conditional closure to the test case.
```php
it('works when using PostgreSQL', function() {
expect(true)->toBeTrue();
})->skip(fn() => DB::getDriverName() !== 'pgsql', 'This test requires a PostgreSQL …
```
=> Closures passed to the `skip` method are now bound to the test case

src/PendingObjects/TestCall.php, tests/Features/Exceptions.php
This PR comes from a discussion with @nunomaduro 
It allows for a user to omit the exception type from a `throws` call and just specify an exception message instead:
```php
it('can just define the message', function () {
throw new Exception('Something bad happened');
})->throws('Something bad happened');
```
=> Allows you to just specify an exception message when calling `throws`.

src/Support/HigherOrderCallables.php, src/Support/HigherOrderTapProxy.php
Previously, calling `tap` in a higher order test would provide no IDE autocomplete suggestions afterwards. This PR resolves that. It also enforces a `TestCase` being passed to the `HigherOrderTapProxy`, because the logic dictates that it would always be a `TestCase` by the time a proxy is resolved.
=> Better tap type hinting

src/Support/HigherOrderCallables.php, tests/Features/HigherOrderTests.php
| Fixed tickets | #343
In the case that the value passed to your `expect` method in higher order tests was an existing function name, the test would fail because that string was callable and the logic used the `is_callable` function. This instead ensures that the value is a `Closure` before treating it as one and binding it to the class.
=> Forces higher order test callable expects to be closures

src/PendingObjects/TestCall.php, src/Support/HigherOrderMessage.php, src/Support/HigherOrderMessageCollection.php, tests/Features/Expect/HigherOrder/methods.php, tests/Features/Expect/HigherOrder/methodsAndProperties.php, tests/Features/Expect/HigherOrder/properties.php
Alrighty,
Up until now, Higher Order Expectations weren't possible in Higher Order Tests. This is because the TestCall had no idea how to handle properties. It also meant that property style expectations didn't work (eg: `expect('foo')->toBeString`).
This PR adds full support for property access in Higher Order Tests, allowing for tests to be written like this:
```php
it('can start a new higher order expectation using the and syntax in higher order tests')
->expect(new HasMethodsAndProperties())
->toBeInstanceOf(HasMethodsAndProperties::class)
->meta->toBeArray
->and(['foo' => 'bar'])
->toBeArray()
->foo->toEqual('bar');
```
Happy Friday!
Luke
=> Adds support for Higher Order Expectations in Higher Order Tests

src/Logging/TeamCity.php
Previously, PhpUnit would show 0 assertions when using the TeamCity test runner:
This was caused by the custom `endTest` method not adding the number of assertions to the logger.
This PR rectifies this:
=> Fixes the assertion output showing as 0 in the TeamCity logger

src/Support/HigherOrderCallables.php, src/Support/Reflection.php, tests/Features/HigherOrderTests.php
Howdy all!
Something that came up in the stream yesterday was the inability to combine higher order tests with datasets. For simplistic tests, this can be quite frustrating. 
This PR updates the higher order callable methods so that they always receive dataset values if available:
```php
it('should throw an InvalidArgumentException')
->with('invalidNames')
->throws(InvalidArgumentException::class)
->tap(fn($name) => ValidatesModuleName::handle($name));
it('converts the markdown to html')
->with('markdownExamples')
->expect(fn($markdown) => MarkdownToHtml::convert($markdown))
->toBeString()
->toStartWith('<p>');
```
Kind Regards,
Luke
=> Higher order callable datasets

src/Laravel/Commands/PestTestCommand.php
From now on with this PR we will be able to create a test with `--flag` and recreate the test file.
=> Add --force flag to pest:test command

src/Concerns/Testable.php, tests/Hooks/AfterAllTest.php, tests/Hooks/BeforeAllTest.php, tests/Pest.php
| Fixed tickets | #351 
The issue is essentially, exactly, as described by @fnzr in the related ticket (great job and good find!).
> Basically, the problem happens because each test, when it's being parsed, registers the global hook on a shared variable (Testable::$beforeAll) as if it were a new hook. The solution would be...well, not do that. [...]
More specifically it is a result of the static nature of these hooks, which is why we do not see this behaviour on the `beforeEach` and `afterEach` variants. This would have been a huge oversight on my part when initially implementing this feature in #282 , and could pose a potential performance issue for some folks, should they be doing any heavy work or …
=> Fix static hooks

src/Expectation.php, tests/Features/Expect/toBeIn.php
This PR adds a new `toBeIn` expectation.
```
expect('a')->toBeIn(['a', 'b', 'c',]); // passes
expect('d')->toBeIn(['a', 'b', 'd',]); // doest not pass
```
=> Add `toBeIn` expectation

src/Exceptions/DatasetMissing.php, src/Factories/TestCaseFactory.php, src/PendingObjects/TestCall.php, src/Repositories/TestRepository.php, src/Support/HigherOrderMessageCollection.php, src/Support/Reflection.php, tests/.snapshots/success.txt, tests/Unit/TestSuite.php
| Fixed tickets | #249 
- add a new exception type, `DatasetMissing`;
- add the new `bool $dependent` property to the test factory to indicate `depends` has been called;
- defaults to `false`;
- we set it to `true` after adding the `addDependencies` factory proxy message from the `TestCall::depends` method;
- make check for datasets within the `TestRepository::set` method;
- we throw the new exception with user-friendly message when all the following are true;
- the test has no dependencies;
- the test has no datasets;
- the test closure has an argument list greater than 0 (checked via reflection);
- add new `Reflection::getFunctionArguments` helper method to return a map of argument names to their types; …
=> Add user-friendly exception message for missing test inputs

src/Expectation.php, tests/.snapshots/success.txt, tests/Features/Expect/toContain.php
This PR adds the ability to pass multiple needles to `->toContain()` expectation:
```php
expect('Nuno')->toContain('Nu', 'no');
```
```php
expect([1, 2, 42])->toContain(42, 2);
```
obviously, it still supports arrays as needles:
```php
expect([[1, 2, 3], 2, 42])->toContain(42, [1, 2, 3]);
```
=> implements multiple needles in expect()->toContain()

composer.json, src/Actions/AddsDefaults.php, src/Concerns/Logging/WritesToConsole.php, src/Logging/TeamCity.php, src/Support/ExceptionTrace.php, tests/.snapshots/success.txt, tests/Features/Expect/json.php, tests/Visual/JUnit.php, tests/Visual/TeamCity.php
This PR aims to add Pest styling to the PhpStorm `TeamCity` Logger. Here are some output examples:
=> Teamcity styling

composer.json, src/Concerns/Testable.php, tests/.snapshots/success.txt, tests/Datasets/Bound.php, tests/Features/Datasets.php
Howdy!
This PR adds support for bound datasets. These datasets have full access to the test case and are resolved after the `beforeEach` has run.
This allows for some really cool scenarios that were never possible before in datasets. For example, you could provide full blown models via datasets:
```php
it('allows any user to be deleted', function(User $user) {
$user->delete();
expect(User::all())->toBeEmpty();
})->with([
fn() => User::factory()->create(),
fn() => User::factory()->blocked()->create(),
fn() => User::factory()->unverified()->create(),
]);
```
This also works with shared datasets:
```php
// Datasets/Users.php
dataset('users', function() {
yield fn() => User::factory()->create();
yield fn() => …
```
=> Datasets can now access the test case

src/Expectation.php, tests/Features/Expect/ToBeFalsy.php, tests/Features/Expect/ToBeTruthy.php
This PR adds `toBeTruthy` and `toBeFalsy`.
Useful when you don't care what a value is and you want to ensure a value is true or false in a boolean context.
```php
expect("true")->toBeTruthy(); // passes
expect("0")->toBeTruthy(); // doest not pass
expect("0")->toBeFalsy(); // passes
expect("false")->toBeFalsy(); // doest not pass
```
=> Add `toBeTruthy` and `ToBeFalsy`

src/Expectation.php, tests/.snapshots/success.txt, tests/Features/Expect/toHaveLength.php
| Fixed tickets | #
Following @nunomaduro's feedback on [#384](https://github.com/pestphp/pest/pull/384)  
Adds the `toHaveLength()` expectation covering strings, arrays, objects and collections.
```php
it('passes', function ($value) {
expect($value)->toHaveLength(9);
})->with([
'Fortaleza', 'Sollefteå', 'Ιεράπετρα', 'PT-BR 🇵🇹🇧🇷😎',
(object) [1, 2, 3, 4, 5, 6, 7, 8, 9],
collect([1, 2, 3, 4, 5, 6, 7, 8, 9]),
]);
it('passes with array', function () {
expect([1, 2, 3])->toHaveLength(3);
});
it('passes with not', function () {
expect([1, 2, 3])->not->toHaveLength(10);
});
```
=> Adds toHaveLength() Expectation & Tests

src/Expectation.php, tests/.snapshots/success.txt, tests/Features/Expect/toHaveLength.php
| Fixed tickets | #
Due to inconsistent behave of grapheme_strlen, mb_strlen will be used.
Even though I could get the expected behaviour when counting emoji texts on a local  windows machine, 
the tests were failing on [#386](https://github.com/pestphp/pest/pull/386)
Thanks for the feeback @nunomaduro
=> Use mb_strlen instead of grapheme_strlen

src/Expectation.php, tests/.snapshots/success.txt, tests/Features/Expect/toHaveProperties.php
This PR adds `ToHaveProperties`.
It is like [toHaveKeys](https://pestphp.com/docs/expectations#expect-toHaveKeys) but for object.
Useful when you want to assert the object has the expected properties but you don't care about the values.
```php
$obj->name = "Jhon";
$obj->age = 21;
expect($obj)->toHaveProperties(["name", "age"]); // passes
expect($obj)->toHaveProperties(["name", "age", "gender"]); // doest not pass
```
=> Add `toHaveProperties`

src/Expectation.php, tests/.snapshots/success.txt, tests/Features/Expect/when.php
It makes some expectations work conditionally.
`when()` is preferably used as an alternative to the `skip()` method, no need to write extra tests.
```php
it('mysql test', function () {
expect(new Foo())
->mysql
->toBeTrue();
})->skip(fn() => DB::getDriverName() === 'mysql', 'Only runs when using mysql');
it('sqlite test', function () {
expect(new Foo())
->sqlite
->toBeTrue();
})->skip(fn() => DB::getDriverName() === 'sqlite', 'Only runs when using sqlite');
```
```php
it('database test', function () {
$driver = DB::getDriverName();
expect(new Foo())
->when($driver === 'mysql',
fn($foo) => $foo->mysql->toBeTrue()
)
->when($driver === 'sqlite',
fn($foo) => $foo->sqlite->toBeTrue()
)
->bar->toEqual('bar'); …
```
=> Adds new `when()` method

src/PendingObjects/TestCall.php, tests/.snapshots/success.txt, tests/Features/Exceptions.php
(snapshots were not updating in this [PR](#362). I forked again.)
I have a test content is about 90 lines. This test content is only compatible with MySQL 8.0+. An exception will be thrown if the MySQL version is less than 8.
I know I can skip this test using Skip. But in this case I will have to create two of the same test. If one is MySQL 8 and above and the other is MySQL 5 it should work.
I can add if-else to test the content.
Or I can create another test with 90 lines.
I chose the fourth alternative, that is, I created a PR :)
```php
function dbVersion() {
return (int) \DB::connection()->getPdo()->getAttribute(\PDO::ATTR_SERVER_VERSION);
}
```
```php
function data() {
if (dbVersion() < 8) {
throw new …
```
=> Add `throwsIf` exception

src/Expectation.php, tests/.snapshots/success.txt, tests/Features/Expect/matchExpectation.php
This is an alternative to #406.
```php
it('database test', function () {
expect(new Foo())
->foo->toBe('foo')
->match(DB::getDriverName(), [
'mysql'  => fn ($foo) => $foo->mysql->toBeTrue(),
'sqlite' => fn ($foo) => $foo->sqlite->toBeTrue(),
])
->bar->toBe('bar');
});
```
```php
it('builder test', function ($driver) {
expect(new Builder())
->match($driver, [
'mysql'   => fn ($b) => $b->where('...')->toBe(...),
'postgre' => fn ($b) => $b->whereRaw('...')->toBe(...),
]);
})->with([
'mysql',
'postgre',
]);
```
For more examples, please review the tests.
Thank you.
=> Adds new `match()` method

src/Expectation.php, tests/.snapshots/success.txt, tests/Features/Expect/sequence.php
| Fixed tickets | #398 
This resolves #398
=> Fix: `sequence()` can generate false positives

src/Factories/TestCaseFactory.php, src/Support/HigherOrderMessageCollection.php, tests/Features/Exceptions.php
This PR will fix skipped text failing if there is a throw expectation (see the test I've added in `tests/Feature/Exceptions.php`)
this test won't be skipped:
```php
it('can handle a skipped test if it is trying to catch an exception', function () {
expect(1)->toBe(2);
})->throws(ExpectationFailedException::class)->skip('this test should be skipped');
```
but it will trigger an error instead:
```
Failed asserting that exception of type "PHPUnit\Framework\SkippedTestError" matches expected exception "PHPUnit\Framework\ExpectationFailedException". Message was: "this test should be skipped"
```
**Edit** I've proposed a cleaner solution than this one, see [this comment](https://github.com/pestphp/pest/pull/413#issuecomment-93269855 …
=> Fix skipping tests with exception asserting

src/Expectation.php
Previously, any string passed to sequence that was also a function name would cause a failure. This fixes that by specifying a closure.
Will port to master too once merged.
=> [1.x] Fix for sequence

src/Factories/TestCaseFactory.php, src/Factories/TestCaseMethodFactory.php
Just going through the Pest source code and made a few little tweaks. These are opinions so feel free to disagree.
The main change is moving the responsibility of generating the test *method* string to `TestCaseMethodFactory`. This serves to reduce the complexity of the large `evaluate` function to make it easier to understand.
=> Small Tweaks for Pest v2

phpstan.neon, src/Concerns/RetrievesValues.php, src/Each.php, src/Expectation.php, src/Functions.php, src/HigherOrderExpectation.php, src/OppositeExpectation.php, src/Support/HigherOrderMessage.php, src/Support/Reflection.php
The purpose of the PR is to improve PHPStan generics on expectations. The goal is that as PhpStorm improves its support for generics, we should get better IDE autocompletion essentially free of charge.
I'm currently getting one issue, which is due to the `Each` type in `HigherOrderExpectation`. If anybody has an idea how we can get this sorted, let me know.
=> [2.x] Improved generics for higher order

composer.json, src/Plugins/Memory.php
| Fixed tickets | ...
This is related to https://github.com/pestphp/pest/issues/375#issuecomment-903183321, and [this message in Discord](https://discord.com/channels/705126275232038944/710642595705126923/905233861615710299).
I've decided to go with outputting `MB`, but I guess we could make it so that it works it out the unit automatically (i.e. B, MB, GB) if that would be better?
Also, I just wanted someone to clarify if `memory_get_usage()` is the correct function to use for this? 🤔
=> feat: add `--memory` usage flag

src/Expectation.php, src/Support/HigherOrderCallables.php, tests/Features/Expect/HigherOrder/methodsAndProperties.php
---
When using `and()` with an expectation, `and()` wraps the expectation into an expectation. That doesn't happen often but it can occur when using something like `sequence()`, where both value and key are already wrapped in an expectation.
```php
it('inspects properties')
->expect(['foo' => ['bar' => 'baz']])
->sequence(
fn ($value, $key) => $value->toBeArray()->and($key->value)->toBe('foo'),
);
```
As the code above shows, we are forced to access the underneath value of the expectation (`$key->value`) to make the test work.
This PR allows `and()` to check if we are passing an expectation - if so, we just return the expectation and don't nest it into a new one. The end result will look like this:
```php …
```
=> Avoid nested expectations with `and()`

src/Expectation.php, tests/Features/Expect/each.php
This PR adds `$key` as a second parameter to `each()` closures.
It is used to retrieve the key of the current item in the array, which is useful when cross-referencing each item to an expected item. For example:
```php
it('can list teams', function () {
/** @var AuthenticatedTestCase $this */
$teams = Team::factory()
->hasAttached($this->user, [], 'members')
->count(5)
->create();
$returnedTeams = getJson(route('api.v2.teams.index'))
->assertSuccessful()
->json('data');
expect($returnedTeams)
->toBeArray()
->each(function (Expectation $returnedTeam, $teamKey) use ($teams) {
$team = $teams[$teamKey];
$returnedTeam
->toBeArray()
->toMatchArray([
'name' => $team->name,
]);
});
});
```
We can use `$teamKey` …
=> feature: Pass `each()` keys to closures

src/HigherOrderExpectation.php, tests/.snapshots/success.txt, tests/Features/Expect/HigherOrder/methods.php
| Fixed tickets | #452
@dansysanalyst and I have been looking into possible solutions for this issue. We have decided on the following:
```php
it('can call the json method in higher order expectations', function () {
expect(new HasMethods())
->getJsonContent()->json()->id->toBe(1)->toBeGreaterThan(0)
->getJsonContent()->json()->email->toBe('amenophis@leherpeur.net');
});
```
Note that at the end of an expectation chain with `json`, the scope will now completely reset, which is in line with how other expectation methods work. Previously, `json` in Higher Order Expectations wasn't working at all.
There was an alternative, which would allow for staying in the JSON object for more expectations on it, but that …
=> Fixes `json` in Higher Order Expectations

src/Support/HigherOrderCallables.php, tests/Features/HigherOrderTests.php
After discussion, we've decided to rename `tap` to `defer` in Higher Order Tests. This PR makes the needed changes for this.
=> Renames `tap` to `defer`.

src/Expectation.php, src/Expectations/HigherOrderExpectation.php, tests/Features/Expect/HigherOrder/methods.php
| Fixed tickets | #452 
This fixes an issue with the `json` expectation method when using Higher Order tests. It is technically breaking, hence v2. I've also taken the opportunity to improve type hinting on the `json` method.
=> Makes `json` expectation usable in Higher Order Tests

src/Expectations/HigherOrderExpectation.php, tests/Features/Expect/HigherOrder/methods.php
This PR adds a new method to Higher Order Expectations: `scoped`. It is partially inspired by Inertia's assertions and allows for more complex expectation chains without additional boilerplate.
Here's an example.
```php
$user = User::find(1);
// Before
expect($user)
->name->toBe('Nuno Maduro')
->email->toBe('foo@bar.com')
->address()->line1->toBe('1 Pest Street')
->address()->city->toBe('Lisbon')
->address()->country->toBe('Portugal')
// After
expect($user)
->name->toBe('Nuno Maduro')
->email->toBe('foo@bar.com')
->address()->scoped(fn ($address) => $address
->line1->toBe('1 Pest Street')
->city->toBe('Lisbon')
->country->toBe('Portugal')
);
```
By using `scoped`, we can by use of a closure lock an …
=> Adds support for `scoped` in HigherOrderExpectations

src/Expectation.php, src/Support/Backtrace.php
this PR will fix some phpstan errors that cause workflows to fail: (e.g [this one](https://github.com/pestphp/pest/actions/runs/1737348776))
**error in `Expectations.php`** 
can be resumed with this [example](https://phpstan.org/r/ba322af4-75b7-4a5d-bd96-66d70090c4de)
fixed with a @phpstan-ignore, but would like to find a more elegant way
**errors in `Support\Backtrace.php`**
can be resumed with this [example](https://phpstan.org/)
fixed adding some `assert(array_key_exists('key', $array));`
=> phpstan fix

src/Mixins/Expectation.php, tests/Features/Expect/toThrow.php
| Fixed tickets | #483 
This PR will fix tests passing when expecting an exception that does not exist
as pointed out in #483 a test like this will pass without revealing the missing Class error:
```php
it("throws the exception", function() {
expect(function() { throw new DoesNotExistException; })
->toThrow(DoesNotExistException::class);
});
```
this is dued to the `->toThrow` expectation checking if its first parameter is a message and not a class:
```php
//Expectation.php lines from 915
if (!class_exists($exception)) {
Assert::assertStringContainsString($exception, $e->getMessage());
return $this;
}
```
in this case:
`$exception` will be `DoesNotExistException`
the class not found error message contained in `$e->getMessage` …
=> Fix toThrow expectation passing when exception doesn't exist

.github/workflows/static.yml, .github/workflows/tests.yml
This doesn't really solve anything, it just makes the output of the CI coloured, which is easier to read than the greyscale scheme.
=> ci: update to use ANSI output

src/Actions/LoadStructure.php, src/Expectation.php, src/Logging/JUnit.php, src/Logging/TeamCity.php, src/Support/Backtrace.php, tests/.snapshots/success.txt, tests/Features/Expect/toThrow.php
fix #483 
basically, it does the same as #484  but had to use a regex to detect the error message, as it is formatted differently in php8 and 7
=> Fix throws missing exception

src/Expectation.php
Adds a `->dump()` helper to Expectation class.
**Usage**
```php
expect(someComplicatedFetchingOrSo())
->dump()
->toBe(...);
```
**Before**
```php
$data = someComplicatedFetchingOrSo();
dump($data);
expect($data)->toBe(...);
```
=> [1.x] Add `dump` helper to Expectation class

src/Factories/Annotations/CoversNothing.php, src/Factories/Attributes/Attribute.php, src/Factories/Attributes/Covers.php, src/Factories/Covers/CoversClass.php, src/Factories/Covers/CoversFunction.php, src/Factories/Covers/CoversNothing.php, src/Factories/TestCaseFactory.php, src/Factories/TestCaseMethodFactory.php, src/PendingCalls/TestCall.php, tests/Features/Covers.php
| Fixed tickets | #32 
This PR _tries_ to implement the `@covers` annotation. Actually, following the issue https://github.com/sebastianbergmann/phpunit/issues/4502 , I decided to implement it as a PHP Attribute since the annotations will be deprecated in PHPUnit 11.
I haven't tested this yet because I started working on it on Windows and 90% of the commands do not work, will come back on this in the next few days.
Because of the logic of Pest (where final user does not have a class), I think it's not possible to implement the `@coversDefaultClass`, but that's not a big deal since the other methods works just fine without it.
**Usage**
```php
test('covers class')
->expect(true)->toBeTrue() …
```
=> [2.x] Add `covers` attribute

src/Factories/Attributes/Attribute.php, src/Factories/TestCaseMethodFactory.php
| Bug fix?      | kinda?
| Fixed tickets | n/a (comment https://github.com/pestphp/pest/pull/492#issuecomment-1062780491)
@nunomaduro this fixes the static types check, sorry!
I had to phpstan-ignore the `__invoke` method because it was complaining about a "missing" final statement on the abstract class method, not 100% sure why.
=> Fix phpstan static errors

src/PendingCalls/TestCall.php, tests/Features/HasNoExpectations.php, tests/Features/ThrowsNoExceptions.php
A feature that is often useful in PHPUnit is `expectNotToPerformAssertions`. This is handy when you have a method that is simply testing that a method can be called without throwing any exceptions or causing any errors, without being interested in the end result.
This PR adds a new `hasNoExpectations` method to the `TestCall` class, which allows us to support this functionality in a style more aligned with Pest:
```php
it('does not throw any errors when run', function () {
SomeComplexService::run();
})->hasNoExpectations();
```
By adding this, we provide 2 main benefits:
1) We allow for visual consistency with other Pest `TestCall` methods, such as `throws`
2) We use the term `expectations` instead of …
=> [2.x] Adds support for chaining `hasNoExpectations` to the test method.

.github/workflows/tests.yml, composer.json
| Bug fix?      | maybe?
| Fixed tickets | N/A
Since [PHPUnit 10 [dropped support for PHP 8.0](https://github.com/sebastianbergmann/phpunit/commit/95b61586c5d9b90bcaa516ddca0af00efc408940), we have to drop it as well for Pest.
=> Drop support for PHP 8.0

src/Mixins/Expectation.php, tests/Features/Expect/toContainOnlyInstancesOf.php
Adds new `containsOnlyInstanceOf` expectation.
=> add new expectation

src/Logging/JUnit.php, src/Support/Printer.php, src/TestCases/IgnorableTestCase.php
This will fix two issue coming from changes in PhpUnit core:
1. `\PHPUnit\Util\Printer` was changed to abstract and its implementation moved to `\PHPUnit\Util\DefaultPrinter` , which is final. I implemented our own Printer that behaves like the old PhpUnit Printer
2. Our `TestSuiteLoader` loaded an **abstract** `IgnorableTestCase` for detected files that shouldn't be loaded. With PhpUnit recent changes, abstract classes now will throw and exception instead to be ignored ([ref](https://github.com/sebastianbergmann/phpunit/commit/32d838252ce3826df7796c1ce557b2c7d56422e7#diff-ce07bbf9be7fe14e3102ab699c8a2d6c2a995bc23f8f93871fb4f3dde098dfaa)), so the trick doesn't work anymore. I changed `IgnorableTestCase` to defined an …
=> Fix issues after PHPUnit refactoring

src/Factories/TestCaseFactory.php
Implements dynamic properties handling in order to avoid deprecation in PHP 8.2
fix https://github.com/pestphp/pest/issues/555
a PR for v2 will follow this one
=> [1.x] Dynamic properties handling

.github/workflows/tests.yml, src/Factories/TestCaseFactory.php, src/Mixins/Expectation.php, tests/Features/Expect/toMatchObject.php
- Fix missing `\` in #[\AllowDynamicProperties]  attribute
- Add PHP8.2 test workflow
- Fix tests failing with PHP8.2
=> 2.x dynamic properties fix
