pestphp/pest

.github/workflows/changelog.yml

Added Changelog headers for website documentation

Update Changelog action

---

.github/workflows/tests.yml
bin/pest
composer.json
src/Console/Command.php
src/Contracts/Plugins/AddsOutput.php
src/Contracts/Plugins/HandlesArguments.php
src/Support/Container.php
tests/.snapshots/success.txt
tests/Unit/Support/Container.php

Add basic container implementation

---

src/Datasets.php
tests/.snapshots/success.txt
tests/Features/Datasets.php

Fix dataset name creation with objects

---

src/Support/HigherOrderMessageCollection.php
src/Support/Reflection.php
tests/.snapshots/success.txt
tests/Features/Macro.php

fixes #108
https://twitter.com/devgummibeer/status/1274639315574894592

pass calls to overloaded method if possible

---

CHANGELOG.md

I'll start with something simple.

docs: updates changelog

---

.editorconfig

For: https://github.com/pestphp/pest/blob/master/rector.yaml

Add yaml file extension support

---

phpunit.xml

chore: update PHPUnit configuration for coverage

---

composer.json

chore: update to use stable Collision 5

---

composer.json

Allow phpunit 9.3.8 too

---

phpunit.xml
stubs/Laravel/phpunit.xml
stubs/Lumen/phpunit.xml

chore: update PHPUnit config stubs

---

.github/workflows/changelog.yml

chore: don't run changelog workflow on forks

---

composer.json

I've also updated to use a version selector, instead of a long list of all the patches that are supported.

chore(composer): add support for PHPUnit 9.3.11

---

composer.json

feat: adds support to PHPUnit 9.4

---

.github/workflows/changelog.yml

ci(changelog): fix changelog action

---

composer.json

chore(deps): add support for PHPUnit 9.4.3

---

RELEASE.md

| Fixed tickets | #224 
This adds a release guide for Pest. I've marked it as draft so we can review it first.
Closes #224

docs: add release guide

---

composer.json

Update PHPUnit dependency version

---

src/Laravel/Commands/PestTestCommand.php
stubs/Browser.php

Add parameter to create Dusk test
[https://github.com/pestphp/pest/issues/244](https://github.com/pestphp/pest/issues/244)
PS: I did not find tests that test these creation commands
PS: the official documentation would have to be modified [https://github.com/pestphp/docs/blob/master/plugins/laravel.md](https://github.com/pestphp/docs/blob/master/plugins/laravel.md)
PS: Sorry for my english

MakeDuskTest

---

composer.json

chore(deps): add support for PHPUnit 9.5.1

---

composer.json

chore(deps): add support for PHPUnit 9.5.2

---

composer.json

chore(deps): add support for PHPUnit 9.5.3

---

src/Laravel/Commands/PestDuskCommand.php

| Fixed tickets | #279
Add Dusk command argument --browse  that was introduced in version 6 of laravel/dusk

Add Dusk command argument --browse

---

src/Actions/LoadStructure.php
src/Concerns/TestCase.php
src/Support/Reflection.php

Remove unused import

---

src/Functions.php

Wrap all functions which are not namespaced in function_exists.

Wrap functions in function_exists

---

composer.json

Closes https://github.com/pestphp/pest/issues/309

Update phpunit/phpunit to 9.5.5

---

CHANGELOG.md
src/PendingObjects/UsesCall.php

| Fixed tickets | N/A
fixes typos

fixes typos

---

src/Concerns/Expectable.php
src/Concerns/Extendable.php
src/Concerns/RetrievesValues.php
src/Expectation.php
src/HigherOrderExpectation.php
tests/.snapshots/success.txt
tests/Features/Expect/HigherOrder/methods.php
tests/Features/Expect/HigherOrder/methodsAndProperties.php
tests/Features/Expect/HigherOrder/properties.php

Reimplements https://github.com/pestphp/pest-plugin-expectations/pull/17 after plugins were merged into core.

Adds Nested Higher Order Expectations

---

stubs/Unit.php

The stub for creating a new unit test through the pest:test command was creating a not working example test.

Fix the unit test stub

---

bin/pest

Fix typography

---

bin/pest
src/Actions/MapArguments.php
src/Console/Paratest/Runner.php

* extracted stuff to `MapArguments`
* implemented `--coverage` output for paratest

Parallel additions

---

src/HigherOrderExpectation.php
tests/.snapshots/success.txt
tests/Features/Expect/HigherOrder/methods.php

Revert "Fixes `json` in Higher Order Expectations"

---

src/Bootstrappers/BootFiles.php
src/Expectation.php

@nunomaduro, just to check, was the `--debug` flag intentionally left in here?
https://github.com/pestphp/pest/blob/master/composer.json#L68

fix: resolve PHPStan warnings

---

src/PendingCalls/TestCall.php
tests/Features/Exceptions.php

Exception codes can be asserted with throws

feat: Add code to the throws arg

---

src/PendingCalls/TestCall.php

fix code style

---

src/Concerns/Pipeable.php
src/Expectation.php
src/Kernel.php
src/Mixins/Expectation.php
src/Repositories/DatasetsRepository.php
src/Support/Container.php
src/Support/HigherOrderMessageCollection.php
tests/Features/Coverage.php
tests/Features/Expect/pipes.php
tests/Features/Expect/toBe.php
tests/Features/Expect/toHaveProperties.php
tests/Features/Expect/unless.php
tests/Features/Expect/when.php
tests/Unit/Support/Reflection.php
tests/Unit/TestSuite.php
tests/Visual/Help.php
tests/Visual/Success.php

Not entirely sure where these came from...

style: apply fixes from PHP-CS-Fixer

---

.gitignore
phpunit.xml
src/Factories/TestCaseFactory.php
src/Support/Reflection.php
tests/Features/Covers.php
tests/Features/Helpers.php

[2.x] Allow Dynamic Properties

---

src/Logging/TeamCity.php
src/Support/ExceptionTrace.php

fix static analysis failing in https://github.com/pestphp/pest/runs/8068835457?check_suite_focus=true
php7.3 tests will be fixed by https://github.com/pestphp/pest-dev-tools/pull/12

1.x fix tests
